package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// HTTP code for type PutServiceIDOK
const PutServiceIDOKCode int = 200

/*PutServiceIDOK Updated

swagger:response putServiceIdOK
*/
type PutServiceIDOK struct {
}

// NewPutServiceIDOK creates PutServiceIDOK with default headers values
func NewPutServiceIDOK() *PutServiceIDOK {
	return &PutServiceIDOK{}
}

// WriteResponse to the client
func (o *PutServiceIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// HTTP code for type PutServiceIDCreated
const PutServiceIDCreatedCode int = 201

/*PutServiceIDCreated Created

swagger:response putServiceIdCreated
*/
type PutServiceIDCreated struct {
}

// NewPutServiceIDCreated creates PutServiceIDCreated with default headers values
func NewPutServiceIDCreated() *PutServiceIDCreated {
	return &PutServiceIDCreated{}
}

// WriteResponse to the client
func (o *PutServiceIDCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
}

// HTTP code for type PutServiceIDInvalid
const PutServiceIDInvalidCode int = 420

/*PutServiceIDInvalid Invalid service configuration

swagger:response putServiceIdInvalid
*/
type PutServiceIDInvalid struct {
}

// NewPutServiceIDInvalid creates PutServiceIDInvalid with default headers values
func NewPutServiceIDInvalid() *PutServiceIDInvalid {
	return &PutServiceIDInvalid{}
}

// WriteResponse to the client
func (o *PutServiceIDInvalid) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(420)
}

// HTTP code for type PutServiceIDFailure
const PutServiceIDFailureCode int = 500

/*PutServiceIDFailure Error while creating service

swagger:response putServiceIdFailure
*/
type PutServiceIDFailure struct {
}

// NewPutServiceIDFailure creates PutServiceIDFailure with default headers values
func NewPutServiceIDFailure() *PutServiceIDFailure {
	return &PutServiceIDFailure{}
}

// WriteResponse to the client
func (o *PutServiceIDFailure) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
